import test from 'node:test';import assert from 'node:assert/strict';import {initialState,legalMoves,move,terrain} from '../dist/engine.mjs';
const p=(rank,team,r,c)=>({id:team+'-'+rank,rank,team,r,c});const s=(pieces,turn='orange')=>({...initialState(),pieces,turn});const has=(st,id,r,c)=>legalMoves(st,id).some(m=>m.r===r&&m.c===c);
test('traditional layout, rivers and dens',()=>{const st=initialState();assert.equal(st.pieces.length,16);assert.equal(st.pieces.find(p=>p.r===8&&p.c===0).rank,6);assert.equal(st.pieces.find(p=>p.r===0&&p.c===6).rank,6);assert.equal(terrain(4,1).type,'water');assert.equal(terrain(4,3).type,'land');assert.equal(terrain(0,3).type,'den');});
test('turns, no diagonals and own den excluded',()=>{const st=initialState();assert.equal(move(st,'blue-1',3,0),null);assert.equal(move(st,'orange-1',5,5),null);const next=move(st,'orange-1',5,6);assert.equal(next.turn,'blue');assert.equal(st.pieces.find(p=>p.id==='orange-1').r,6);assert.equal(has(s([p(2,'orange',7,3)]),'orange-2',8,3),false);});
test('only rat swims; no capture across shore',()=>{assert(has(s([p(1,'orange',3,0)]),'orange-1',3,1));assert(!has(s([p(2,'orange',3,0)]),'orange-2',3,1));assert(!has(s([p(1,'orange',3,0),p(1,'blue',3,1)]),'orange-1',3,1));assert(!has(s([p(1,'orange',3,1),p(8,'blue',3,0)]),'orange-1',3,0));assert(has(s([p(1,'orange',3,1),p(1,'blue',3,2)]),'orange-1',3,2));});
test('rat beats elephant; elephant cannot take rat; ranks enforced',()=>{assert(has(s([p(1,'orange',4,3),p(8,'blue',3,3)]),'orange-1',3,3));assert(!has(s([p(8,'orange',4,3),p(1,'blue',3,3)]),'orange-8',3,3));assert(!has(s([p(2,'orange',4,3),p(3,'blue',3,3)]),'orange-2',3,3));assert(has(s([p(5,'orange',4,3),p(5,'blue',3,3)]),'orange-5',3,3));});
test('horizontal and vertical leaps; either rat blocks; capture rank enforced',()=>{assert(has(s([p(6,'orange',4,0)]),'orange-6',4,3));assert(has(s([p(7,'orange',6,1)]),'orange-7',2,1));for(const team of ['blue','orange'])assert(!has(s([p(6,'orange',4,0),p(1,team,4,2)]),'orange-6',4,3));assert(!has(s([p(6,'orange',4,0),p(8,'blue',4,3)]),'orange-6',4,3));assert(has(s([p(6,'orange',4,0),p(5,'blue',4,3)]),'orange-6',4,3));});
test('enemy traps weaken even rats; own traps do not',()=>{assert(has(s([p(2,'orange',7,2),p(8,'blue',8,2)]),'orange-2',8,2));assert(has(s([p(8,'orange',7,2),p(1,'blue',8,2)]),'orange-8',8,2));assert(!has(s([p(2,'orange',1,2),p(8,'blue',0,2)]),'orange-2',0,2));});
test('den victory and all animals captured',()=>{assert.equal(move(s([p(2,'orange',1,3),p(1,'blue',2,0)]),'orange-2',0,3).winner,'orange');const next=move(s([p(4,'orange',4,3),p(2,'blue',3,3)]),'orange-4',3,3);assert.equal(next.winner,'orange');assert.equal(next.pieces.length,1);assert.equal(legalMoves(next,'orange-4').length,0);});
